In [1]:
import pandas as pd
import pickle
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split,cross_validate,StratifiedKFold
from sklearn import svm
from keras.utils import to_categorical

Using TensorFlow backend.


In [2]:
X=pd.read_csv("data\X.csv", sep=' ',header=None, dtype=float)
X=X.values
Y=pd.read_csv("data\y_williams_vs_others.csv", header=None)
y = Y.values.ravel()
print(X.shape)
print(y.shape)
print(np.sum(y))

(13233, 4096)
(13233,)
52


In [38]:
print(X)
print(y)
y_cat = to_categorical(y)
classes = np.unique(y)
nClasses = len(classes)
print(nClasses)
print(y_cat)

[[0.10635443 0.09975202 0.11191927 ... 0.04983379 0.05402631 0.04627987]
 [0.         0.         0.         ... 0.00410788 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.00074521 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.00030042 0.         0.        ]]
[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
2
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]


In [55]:
X1=X.reshape(-1,64,64,1)
X_train, X_test, y_train, y_test = train_test_split(X1, y, shuffle = True,stratify=y, test_size=1./3, random_state=8401)

In [56]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(np.sum(y_train))
print(np.sum(y_test))

(8822, 64, 64, 1)
(4411, 64, 64, 1)
(8822,)
(4411,)
35
17


In [ ]:
from keras import layers
from keras import models
from keras.layers.core import Activation
model = models.Sequential()
model.add(layers.Conv2D(32,(3,3),activation='tanh',input_shape=(64,64,1)))
model.add(layers.MaxPooling2D(pool_size=(2, 2),strides=(2,2)))
model.add(layers.Conv2D(32, (3, 3),activation='tanh'))
model.add(layers.MaxPooling2D(pool_size=(2, 2),strides=(2,2)))
model.add(layers.Conv2D(64, (3, 3),activation='tanh'))
model.add(layers.MaxPooling2D(pool_size=(2, 2),strides=(2,2)))
model.add(layers.Dropout(0.4))
model.add(layers.Flatten())
model.add(layers.Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()
#train_X=X_train.reshape(-1,64,64,1)
model.fit(X_train,y_train,batch_size=64,epochs=10)
predict_function1= model.predict_classes(X_train)
predict_function= model.predict_classes(X_test)
from sklearn.metrics import f1_score
f1_williams=f1_score(y_test,predict_function)
f1_williams1=f1_score(y_train,predict_function1)
print(f1_williams1)
print(f1_williams)


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_61 (Conv2D)           (None, 62, 62, 32)        320       
_________________________________________________________________
max_pooling2d_61 (MaxPooling (None, 31, 31, 32)        0         
_________________________________________________________________
conv2d_62 (Conv2D)           (None, 29, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_62 (MaxPooling (None, 14, 14, 32)        0         
_________________________________________________________________
conv2d_63 (Conv2D)           (None, 12, 12, 64)        18496     
_________________________________________________________________
max_pooling2d_63 (MaxPooling (None, 6, 6, 64)          0         
_________________________________________________________________
dropout_15 (Dropout)         (None, 6, 6, 64)          0         
__________

In [ ]:
model.save('williams.model')
from keras.models import load_model
model_final=load_model('williams.model')
model_final.summary()

In [66]:
model.save('williams.model')
from keras.models import load_model
model_final=load_model('williams.model')
model_final.summary()

NameError: name 'model2' is not defined

In [45]:
from keras import layers
from keras import models
from keras.layers.core import Activation
model3 = models.Sequential()
model3.add(layers.Conv2D(32,(3,3),activation='tanh',input_shape=(64,64,1)))
model3.add(layers.MaxPooling2D(pool_size=(2, 2),strides=(2,2)))
model3.add(layers.Conv2D(32, (3, 3),activation='tanh'))
model3.add(layers.MaxPooling2D(pool_size=(2, 2),strides=(2,2)))
model3.add(layers.Conv2D(64, (3, 3),activation='tanh'))
model3.add(layers.MaxPooling2D(pool_size=(2, 2),strides=(2,2)))
model3.add(layers.Dropout(0.4))
model3.add(layers.Flatten())
model3.add(layers.Dense(1, activation='sigmoid'))
model3.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model3.summary()
train_X=X_train.reshape(-1,64,64,1)
model3.fit(train_X,y_train,batch_size=64,epochs=10)
predict_function1= model3.predict_classes(train_X)
predict_function= model3.predict_classes(test_X)
from sklearn.metrics import f1_score
f1_williams=f1_score(y_test,predict_function)
f1_williams1=f1_score(y_train,predict_function1)
print(f1_williams1)
print(f1_williams)


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_55 (Conv2D)           (None, 62, 62, 32)        320       
_________________________________________________________________
max_pooling2d_55 (MaxPooling (None, 31, 31, 32)        0         
_________________________________________________________________
conv2d_56 (Conv2D)           (None, 29, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_56 (MaxPooling (None, 14, 14, 32)        0         
_________________________________________________________________
conv2d_57 (Conv2D)           (None, 12, 12, 64)        18496     
_________________________________________________________________
max_pooling2d_57 (MaxPooling (None, 6, 6, 64)          0         
_________________________________________________________________
dropout_13 (Dropout)         (None, 6, 6, 64)          0         
__________

In [58]:
model3.save('model3')
del model3
from keras.models import load_model
model_final=load_model('model3')
model_final.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_55 (Conv2D)           (None, 62, 62, 32)        320       
_________________________________________________________________
max_pooling2d_55 (MaxPooling (None, 31, 31, 32)        0         
_________________________________________________________________
conv2d_56 (Conv2D)           (None, 29, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_56 (MaxPooling (None, 14, 14, 32)        0         
_________________________________________________________________
conv2d_57 (Conv2D)           (None, 12, 12, 64)        18496     
_________________________________________________________________
max_pooling2d_57 (MaxPooling (None, 6, 6, 64)          0         
_________________________________________________________________
dropout_13 (Dropout)         (None, 6, 6, 64)          0         
__________

In [54]:
predict_function1= model_final.predict_classes(train_X)
predict_function= model_final.predict_classes(test_X)
from sklearn.metrics import f1_score
f1_williams=f1_score(y_test,predict_function)
f1_williams1=f1_score(y_train,predict_function1)
print(f1_williams1)
print(f1_williams)

0.0
0.0


In [27]:
train_X=X_train.reshape(-1,64,64,1)
model.fit(train_X,y_train,batch_size=64,epochs=5)

Epoch 1/5
8822/8822 [==============================] - 336s 38ms/step - loss: 0.0632 - acc: 0.9960
Epoch 2/5
8822/8822 [==============================] - 334s 38ms/step - loss: 0.0639 - acc: 0.9960
Epoch 3/5
8822/8822 [==============================] - 331s 38ms/step - loss: 0.0639 - acc: 0.9960
Epoch 4/5
8822/8822 [==============================] - 329s 37ms/step - loss: 0.0639 - acc: 0.9960
Epoch 5/5
8822/8822 [==============================] - 259s 29ms/step - loss: 0.0639 - acc: 0.9960


In [29]:
test_X=X_test.reshape(-1,64,64,1)
print(test_X.shape)
scores = model3.evaluate(test_X, y_test)


(4411, 64, 64, 1)
4411/4411 [==============================] - 7s 2ms/step


In [44]:
print(scores)

[0.062119256566724464, 0.9961459987748915]


In [30]:
predict_function= model3.predict_classes(test_X)

In [31]:
from sklearn.metrics import f1_score
f1_williams=f1_score(y_test,predict_function)
print(f1_williams)

0.0


c:\users\spver\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


In [46]:
model1.add(Conv2D(64, (3, 3), padding = 'same'))
#model.add(BatchNormalization())
model1.add(Activation('relu'))
model1.add(MaxPooling2D(pool_size=(2, 2)))

model1.add(Flatten()) 
model1.add(Dense(128))
model1.add(Activation('relu'))                
model1.add(Dense(64))
model1.add(Activation('relu'))
model1.add(Dropout(0.5))
model1.add(Dense(1))
model1.add(Activation('sigmoid'))

model1.summary()

NameError: name 'model1' is not defined

In [60]:
from keras.utils import plot_model
plot_model(model, to_file='model.png')

NameError: name 'model' is not defined

In [64]:
model.save('williams.model')

NameError: name 'model' is not defined

In [69]:
model3.save('williams.modal')
from keras.models import load_model
model_final=load_model('williams.modal')
model_final.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_55 (Conv2D)           (None, 62, 62, 32)        320       
_________________________________________________________________
max_pooling2d_55 (MaxPooling (None, 31, 31, 32)        0         
_________________________________________________________________
conv2d_56 (Conv2D)           (None, 29, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_56 (MaxPooling (None, 14, 14, 32)        0         
_________________________________________________________________
conv2d_57 (Conv2D)           (None, 12, 12, 64)        18496     
_________________________________________________________________
max_pooling2d_57 (MaxPooling (None, 6, 6, 64)          0         
_________________________________________________________________
dropout_13 (Dropout)         (None, 6, 6, 64)          0         
__________